version: '3.9'

services:
  db:
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: rNyuWJxjKv2Bntnus2muVHTFzsPjp
    ports:
      - 5432:5432

volumes:
  db:
